/**
 * Application Version Constants
 *
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated by scripts/sync-version.js
 * Source of truth: package.json "version" field
 *
 * To update version:
 * 1. Edit version in package.json
 * 2. Run: pnpm run sync:version (or automatically via prebuild/predev)
 *
 * Generated at: 2026-08-08T02:57:34.498Z
 */

/**
 * Application version number (e.g., "0.1.0")
 */
export const APP_VERSION = '1.5.0' as const;

/**
 * Application version with 'v' prefix (e.g., "v0.1.0")
 * Commonly used for display purposes
 */
export const APP_VERSION_WITH_PREFIX = 'v1.5.0' as const;

/**
 * Parse version into components
 */
export const VERSION_PARTS = {
  major: 1,
  minor: 5,
  patch: 0,
} as const;
