/**
 * Application Version Constants
 *
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated by scripts/sync-version.js
 * Source of truth: package.json "version" field
 *
 * To update version:
 * 1. Edit version in package.json
 * 2. Run: npm run sync:version (or automatically via prebuild/predev)
 *
 * Generated at: 2025-12-29T02:07:42.727Z
 */

/**
 * Application version number (e.g., "0.1.0")
 */
export const APP_VERSION = '0.4.1' as const;

/**
 * Application version with 'v' prefix (e.g., "v0.1.0")
 * Commonly used for display purposes
 */
export const APP_VERSION_WITH_PREFIX = 'v0.4.1' as const;

/**
 * Parse version into components
 */
export const VERSION_PARTS = {
  major: 0,
  minor: 4,
  patch: 1,
} as const;
